apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wpcli
  labels:
    app: wpcli
spec:
  selector:
    matchLabels:
      app: wpcli
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wpcli
        tier: frontend
    spec:
      containers:
      - image: wordpress:cli
        name: wpcli
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql
        - name: WORDPRESS_DB_USER
          value: root
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: mysql-root-password
        ports:
        - containerPort: 80
          name: wpcli
        volumeMounts:
        - name: wps
          mountPath: /var/www/html
      volumes:
      - name: wps
        persistentVolumeClaim:
          claimName: wpcli-pvc