apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: djibysow/wordpress:1.1
        name: wordpress
        command: ["wp"]
        args: ["core", "install", "--url=http://localhost:31909", "--title=Example", "--admin_user=wango", "--admin_password=p@ssw0rd", "--allow-root"]
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql
        - name: WORDPRESS_DB_USER
          value: root
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: mysql-root-password
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wps
          mountPath: /var/www/html
      volumes:
      - name: wps
        persistentVolumeClaim:
          claimName: wordpress-pvc